image:
  repository: b4bz/homer
  tag: latest
  pullPolicy: IfNotPresent

service:
  port:
    port: 8080

ingress:
  enabled: true

persistence:
  config:
    enabled: true
    emptyDir: true
    mountPath: /www/assets

addons:
  codeserver:
    enabled: true
    workingDir: "/www/assets"
    ingress:
      enabled: true
    volumeMounts:
    - name: config
      mountPath: /www/assets
    
fixMountPermissions: false
appVolumeMounts:
  data:
    enabled: true
    emptyDir: true
    datasetName: "data"
    mountPath: "/data"
    hostPathEnabled: true
    hostPath: "/tmp"
  test:
    enabled: true
    emptyDir: true
    datasetName: "test"
    mountPath: "/test"
    hostPathEnabled: true
    hostPath: "/tmp"
    
appAdditionalServicesEnabled: true
appAdditionalServices:
  extra-tcp:
    enabled: true
    type: ClusterIP
    port:
      port: 51414
      name: tcp-test
      protocol: TCP
      targetPort: 51414
  extra-udp:
    enabled: true
    type: ClusterIP
    port:
      port: 51414
      name: udp-test
      protocol: UDP
      targetPort: 51414