# Default values for common-test.
# Use jackett because it's a nice basic app...
image:
  repository: ghcr.io/truecharts/jackett
  pullPolicy: IfNotPresent
  tag: v0.17.671

strategy:
  type: Recreate


services:
  main:
    enabled: true
    port:
      port: 9117

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

services:
  main:
    enabled: true
    port:
      port: 9117

additionalServices:
  - name: test3
    enabled: true
    type: ClusterIP
    port:
      port: 8083
      name: extra-tcp-test
      protocol: TCP
      targetPort: 8083
  - name: test4
    enabled: true
    type: ClusterIP
    port:
      port: 8084
      name: extra-udp-test
      protocol: UDP
      targetPort: 8084

ingress:
  test1:
    enabled: true
  test2:
    certType: "plain"

additionalIngress:
  - name: "test3"
    enabled: true
  - name: "test4"
    enabled: true

persistence:
    config:
    enabled: true
    mountPath: "/config"
    emptyDir: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""

# these values and names are set specifically with the unittests in mind.
customStorage:
  - enabled: true
    emptyDir: true
    mountPath: "/test3"
    hostPath: ""
  - name: "test4"
    enabled: true
    emptyDir: false
    setPermissions: true
    mountPath: "/test4"
    hostPath: "/tmp"

deviceMounts:
  test1:
    enabled: true
    emptyDir: true
    devicePath: "/test1"
  test2:
    enabled: true
    emptyDir: false
    devicePath: "/test2"
