# See https://pre-commit.com for more information
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: end-of-file-fixer
    exclude: '\.github(.+)'
  - id: trailing-whitespace
    exclude: '\.github(.+)'
