image:
  repository: b4bz/homer
<<<<<<< HEAD
  tag: latest
  pullPolicy: IfNotPresent

service:
  port:
    port: 8080

ingress:
  enabled: true
=======
  tag: 21.03.2
  pullPolicy: IfNotPresent

services:
  main:
    port:
      port: 8080
  test1:
    enabled: true
    type: ClusterIP
    port:
      port: 8081
      name: tcp-test
      protocol: TCP
      targetPort: 8081
  test2:
    enabled: true
    type: ClusterIP
    port:
      port: 8082
      name: udp-test
      protocol: UDP
      targetPort: 8082

additionalServices:
  - name: test3
    enabled: true
    type: ClusterIP
    port:
      port: 8083
      name: extra-tcp-test
      protocol: TCP
      targetPort: 8083
  - name: test4
    enabled: true
    type: ClusterIP
    port:
      port: 8084
      name: extra-udp-test
      protocol: UDP
      targetPort: 8084

ingress:
  test1:
    enabled: true
  test2:
    enabled: true

additionalIngress:
  - name: "test3"
    enabled: true
  - name: "test4"
    enabled: true
>>>>>>> df05cf8ce687f8235ce0cb1d2ea042a31047123a

# these values and names are set specifically with the unittests in mind.
fixMountPermissions: false
appVolumeMounts:
  test1:
    enabled: true
    emptyDir: true
    datasetName: "test1"
    mountPath: "/test1"
    hostPathEnabled: false
    hostPath: ""
  test2:
    enabled: true
    emptyDir: false
    datasetName: "test2"
    mountPath: "/test2"
    hostPathEnabled: true
    hostPath: "/tmp"

# these values and names are set specifically with the unittests in mind.
additionalAppVolumeMounts:
  - name: "test3"
    enabled: true
    emptyDir: true
    datasetName: "test3"
    mountPath: "/test3"
    hostPathEnabled: false
    hostPath: ""
  - name: "test4"
    enabled: true
    emptyDir: false
    datasetName: "test4"
    mountPath: "/test4"
    hostPathEnabled: true
    hostPath: "/tmp"
<<<<<<< HEAD

appAdditionalServicesEnabled: true
appAdditionalServices:
  extra-tcp:
    enabled: true
    type: ClusterIP
    port:
      port: 51414
      name: tcp-test
      protocol: TCP
      targetPort: 51414
  extra-udp:
    enabled: true
    type: ClusterIP
    port:
      port: 51414
      name: udp-test
      protocol: UDP
      targetPort: 51414
=======
>>>>>>> df05cf8ce687f8235ce0cb1d2ea042a31047123a
