image:
  repository: b4bz/homer
  tag: latest
  pullPolicy: IfNotPresent

service:
  port:
    port: 8080

ingress:
  enabled: true

# these values and names are set specifically with the unittests in mind.
fixMountPermissions: false
appVolumeMounts:
  test1:
    enabled: true
    emptyDir: true
    datasetName: "test1"
    mountPath: "/test1"
    hostPathEnabled: false
    hostPath: ""
  test2:
    enabled: true
    emptyDir: false
    datasetName: "test2"
    mountPath: "/test2"
    hostPathEnabled: true
    hostPath: "/tmp"

# these values and names are set specifically with the unittests in mind.
additionalAppVolumeMounts:
  - name: "test3"
    enabled: true
    emptyDir: true
    datasetName: "test3"
    mountPath: "/test3"
    hostPathEnabled: false
    hostPath: ""
  - name: "test4"
    enabled: true
    emptyDir: false
    datasetName: "test4"
    mountPath: "/test4"
    hostPathEnabled: true
    hostPath: "/tmp"

appAdditionalServicesEnabled: true
appAdditionalServices:
  extra-tcp:
    enabled: true
    type: ClusterIP
    port:
      port: 51414
      name: tcp-test
      protocol: TCP
      targetPort: 51414
  extra-udp:
    enabled: true
    type: ClusterIP
    port:
      port: 51414
      name: udp-test
      protocol: UDP
      targetPort: 51414
