# Default values for bitwardenrs.

replicaCount: 1

image:
  repository: bitwardenrs/server
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  port:
    port: 80
    
env: 
# If you plan to run the WebUI on a port other than port 80, specify that here:
# For example, if running the container as a non-root user.
#  ROCKET_PORT: "80"
  DATABASE_URL: "/database/bitwarden.sqlite3"

persistence:
  data:
    enabled: false
    emptyDir: false
    mountPath: /data



appIngressEnabled: true
