apiVersion: v2
name: common
description: Function library for TrueCharts
type: library
version: 1.3.0

kubeVersion: ">=1.16.0-0"
# upstream_version: 3.0.1
keywords:
  - truecharts
  - library-chart
  - k8s-at-home
  - common
home: https://github.com/truecharts/truecharts/tree/master/common
maintainers:
  - name: truecharts
