apiVersion: v2
name: bitwardenrs
description: Unofficial Bitwarden compatible server written in Rust
type: application
version: 1.3.3
appVersion: 1.19.0
keywords:
  - bitwarden
  - bitwardenrs
  - bitwarden_rs
  - password
  - rust
home: https://github.com/drlike/truecharts/tree/master/charts/bitwardenrs
sources:
  - https://github.com/k8s-at-home/charts/tree/master/charts/bitwardenrs
  - https://github.com/dani-garcia/bitwarden_rs
maintainers:
  - name: 
    email: 
icon: https://raw.githubusercontent.com/bitwarden/brand/master/icons/256x256.png
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.6.7
